### ISSUE TITLE
Chinese, Japanese and other characters cannot be input

### ISSUE THREAD

**Issue by Zimengzhou** [gitbito/CLI#1]

**Comment by Jeffrey-Morgan** [comment]
Need this feature too! Hope release soon with this feature

**Comment by bitoandy** [comment]
Hi @Jeffrey-Morgan ,

We are working on enabling this in the next version update.

**Comment by bitoandy** [comment]
Hi All, with the latest version (3.0) support to allow languages like Chinese, Japanese, Korean, etc has been added. Please try it out and let us know if you see any issues.
