### ISSUE TITLE
Unable to reply content in markdown format

### ISSUE THREAD

**Issue by 1226085293** [gitbito/CLI#10]
![image](https://user-images.githubusercontent.com/45589707/236890329-a679c8d5-6fe3-4be3-9eb4-c73a95c29c4a.png)

**Comment by 1226085293** [comment]
Always missing ``` enclosing symbols

**Comment by bitoandy** [comment]
Thanks for the feedback, we will look at adding this in the next update.

**Comment by bitoandy** [comment]
@1226085293 ,

With the latest release 3.1 this is fixed. Please update/install bito again to get the new version, checkout the screen shots below.
In interactive mode:
<img width="1028" alt="Screenshot 2023-05-18 at 9 50 05 AM" src="https://github.com/gitbito/CLI/assets/125080245/c6d3648b-588f-4545-b04f-5389d9c5f0c6">

In non-interactive mode:
<img width="1028" alt="Screenshot 2023-05-18 at 9 51 03 AM" src="https://github.com/gitbito/CLI/assets/125080245/688cd908-1483-41f5-a96a-a3bb381dc964">

**Comment by macky3099** [comment]
@1226085293 Let us know if this solves the issue and if we can close this issue.

**Comment by MushahidBrohi** [comment]
00111110010
