### ISSUE TITLE
error when installion on MacOS

### ISSUE THREAD

**Issue by zzzgit** [gitbito/CLI#13]
On MacOS.

`sudo curl https://alpha.bito.co/downloads/cli/install.sh -fsSL | bash`

<img width="412" alt="image" src="https://github.com/gitbito/CLI/assets/1060733/a440fa40-4260-4357-91de-bbdc3df45df3">

However, I can use bito normally. The error has no impact on using.

**Comment by macky3099** [comment]
Hello @zzzgit 

Thank you for saving and posting your observation.

To help us understand the issue better can you provide some additional information such as if you were able to use bito after this installation as the last line in your screenshot indicates that Bito CLI was successfully installed.

Also do you have any settings which can alter the default behaviour or path of files and folders?

**Comment by zzzgit** [comment]
> Hello @zzzgit
> 
> Thank you for saving and posting your observation.
> 
> To help us understand the issue better can you provide some additional information such as if you were able to use Bito CLI after this installation as the last line in your screenshot indicates that Bito CLI was successfully installed.
> 
> Also do you have any settings which can alter the default behaviour or path of files and folders?

I updated my post, I can use it with no problem.

**Comment by macky3099** [comment]
@zzzgit Thank you for the update. 

We will still try to figure out what caused the issue.
