### ISSUE TITLE
acces to bito history from the command line

### ISSUE THREAD

**Issue by redscorpse** [gitbito/CLI#14]
Could you allow to access to bito's history from the command line, please?

**Comment by macky3099** [comment]
Hello @redscorpse,

Navigating through history via arrow keys isn't supported in the current Bito CLI interface. But we will add the support for it and make it available in the next release.

Thanks!

**Comment by redscorpse** [comment]
Cool! Nice project :)

**Comment by macky3099** [comment]
Hi @redscorpse, 

We made a small release for some bug fixes which doesn't contain the history related feature but we are working on it and will notify you with its release.

Thanks!

**Comment by basbs** [comment]
Looking forward for this feature.

**Comment by yfdyh000** [comment]
BTW, I wish the history could be browsed from the VS Code extension, as well as labeled.
