### ISSUE TITLE
Question about bito CLI usage and repeated captcha prompts

### ISSUE THREAD

**Issue by hthappy** [gitbito/CLI#15]
Hello,

I tried running the command "bito -p 1.txt -f 1.py -c 1.log," but it returned an empty value. Additionally, when running bito, I keep receiving prompts to enter a captcha repeatedly.

I would like to know if this behavior is normal. Any insights or guidance on this matter would be greatly appreciated.

Thank you.

**Comment by macky3099** [comment]
Hello @hthappy 

Thank you for your post. Can you please paste a screenshot of what you see on the Bito CLI interface, especially the captcha part? 

Because the prompt to enter captcha that you sse is not the part of Bito CLI's any feautre functionality. We would need some more details like a screenshot, machine you are using, and also if you are able to run "bito" command normally and interact with it smoothly?

Thanks!

**Comment by hthappy** [comment]
> 你好@hthappy
> 
> 谢谢你的文章。您能否粘贴您在 Bito CLI 界面上看到的屏幕截图，尤其是验证码部分？
> 
> 因为您看到的输入验证码的提示不是 Bito CLI 的任何功能的一部分。我们需要更多详细信息，例如屏幕截图、您正在使用的机器，以及您是否能够正常运行“bito”命令并顺利地与其交互以了解实际情况。
> 
> 谢谢！

hello @macky3099 

Every time I enter Bito's regular chat mode, I have to re-enter the verification code. I remember that in the previous version, it was not necessary to enter the verification code every time. Sometimes, during the input of the verification code, I am unable to enter any content. The interface remains unaffected, and I can only close the terminal and reopen it.

Using the command doesn't return any content: `bito -p prompt.txt -f test.py`

```
Tao@Macbook ~ % cat prompt.txt
Explain this code

Tao@Macbook ~ % cat test.py
def bubble_sort(lst):
  n = len(lst)
  for i in range(n-1):
    for j in range(n-1-i):
      if lst[j] > lst[j+1]:
        lst[j], lst[j+1] = lst[j+1], lst[j]
  return lst

lst = [5, 3, 8, 2, 9, 1]
print(bubble_sort(lst)
```

![bito-1](https://github.com/gitbito/CLI/assets/29004012/4b7d253d-d729-43db-9506-808ca2255a5a)
![bito](https://github.com/gitbito/CLI/assets/29004012/a416e565-f69d-46e8-8a33-2d35c86f6b6c)

**Comment by hthappy** [comment]
> Hello @hthappy
> 
> Thank you for your post. Can you please paste a screenshot of what you see on the Bito CLI interface, especially the captcha part?
> 
> Because the prompt to enter captcha that you see is not the part of Bito CLI's any feature functionality. We would need some more details like a screenshot, machine you are using, and also if you are able to run "bito" command normally and interact with it smoothly to get to know what's really happening.
> 
> Thanks!

Hello @macky3099 

Every time I enter Bito's regular chat mode, I have to re-enter the verification code. I remember that in the previous version, it was not necessary to enter the verification code every time. Sometimes, during the input of the verification code, I am unable to enter any content. The interface remains unaffected, and I can only close the terminal and reopen it.

Using the command doesn't return any content: `bito -p prompt.txt -f test.py`

```
Tao@Macbook ~ % cat prompt.txt
Explain this code

Tao@Macbook ~ % cat test.py
def bubble_sort(lst):
  n = len(lst)
  for i in range(n-1):
    for j in range(n-1-i):
      if lst[j] > lst[j+1]:
        lst[j], lst[j+1] = lst[j+1], lst[j]
  return lst

lst = [5, 3, 8, 2, 9, 1]
print(bubble_sort(lst))
```
![bito](https://github.com/gitbito/CLI/assets/29004012/64108f1b-8cf5-4892-8af3-e661f1603c26)
![bito-1](https://github.com/gitbito/CLI/assets/29004012/7e3d5864-6a83-418b-a09e-ceddfcadf1ca)

**Comment by bitoandy** [comment]
@hthappy ,

Sorry about the issue, we have found the issue and are fixing it, will update you once the fix is live which should be within 2 hours.
