### ISSUE TITLE
Reached token limit, How many characters is the limit?

### ISSUE THREAD

**Issue by pkptzx** [gitbito/CLI#18]
`Reached token limit, please try again by reducing AI input`

Reached token limit, How many characters is the limit?

**Comment by nisha-bito** [comment]
hi @pkptzx ,

We have limitations of 4k tokens, and some requests can go up to 6-7k tokens.  We are looking at how to improve this. 
You can also try initiate a new Session by clicking on + button at top. This will clear the previous contexts of questions giving more token for the new question. 

Thanks,
Nisha

**Comment by pkptzx** [comment]
Thanks for answering
