### ISSUE TITLE
Sorry, Bito is not reachable due to a network or server issue. Please try again 

### ISSUE THREAD

**Issue by monkeyshichi** [gitbito/CLI#22]
Sorry, Bito is not reachable due to a network or server issue. Please try again

**Comment by bitoandy** [comment]
Hi @monkeyshichi ,

As mentioned on: https://github.com/gitbito/bitoai/issues/100
If the access to bito.ai domains is blocked, Bito CLI and IDE extensions will not work.
You will need to use network which allows access to bito.ai domains and its sub domains.
