### ISSUE TITLE
curl: (60) SSL certificate problem:

### ISSUE THREAD

**Issue by rezabaharmand** [gitbito/CLI#23]
Hi,
good day.
when I run the command in terminal, I got his error:

curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I read the article, but I didn't understand how to fix this error.

**Comment by bitoandy** [comment]
Hi @rezabaharmand ,

We have recently changed domains from Bito.co to Bito.ai, we have now updated the instructions for installation.
Please try using the following command line to install.
```sudo curl https://alpha.bito.ai/downloads/cli/install.sh -fsSL | bash```
Let us know if you still face issues.

**Comment by rezabaharmand** [comment]
Hi @bitoandy ,
Good day.
I solved the issue with this method at below : 
I used: " brew install curl ", then : " export PATH="/usr/local/opt/curl/bin:$PATH"  ", and at the end : 
" sudo curl https://alpha.bito.ai/downloads/cli/install.sh -fsSL | bash " .

Bito CLI installed and worked fine.

Have a good day.
