### ISSUE TITLE
No hint indicating installation was successful in BitoCLI.msi

### ISSUE THREAD

**Issue by yfdyh000** [gitbito/CLI#27]
In Windows 10. The installation is completed, but the installer is quietly exit.

**Comment by bitoandy** [comment]
Thanks @yfdyh000 for reporting this, we will fix this in the next version update.

**Comment by macky3099** [comment]
Hi @yfdyh000, with the new version of Bito CLI 3.5, this should be fixed. You can try out the new windows installer from version 3.5 and check if you still face any issues.

Please report back to us in case you face any issues.

Thanks!

**Comment by macky3099** [comment]
Hello @yfdyh000, we are closing this issue for now. Please feel free to reopen it if you face any issues. Thanks!
