### ISSUE TITLE
The last code fragment not end in ```

### ISSUE THREAD

**Issue by liuzhenghua** [gitbito/CLI#35]
![image](https://github.com/gitbito/CLI/assets/11787325/73da3378-6152-4ea4-b65e-a862c73f7e0d)

**Comment by macky3099** [comment]
Hello @liuzhenghua, 

Can you please try to regenerate the response and see if you are getting this all the time?

Thanks!

**Comment by liuzhenghua** [comment]
> Hello @liuzhenghua,
> 
> Can you please try to regenerate the response and see if you are getting this all the time?
> 
> Thanks!

It happens

> Hello @liuzhenghua,
> 
> Can you please try to regenerate the response and see if you are getting this all the time?
> 
> Thanks!

It happens frequently, but not every time.

**Comment by liuzhenghua** [comment]
> Hello @liuzhenghua,
> 
> Can you please try to regenerate the response and see if you are getting this all the time?
> 
> Thanks!

It happens frequently, but not every time.

**Comment by liuzhenghua** [comment]
![image](https://github.com/gitbito/CLI/assets/11787325/3222c136-fe88-446b-8a24-ab4e55044551)

**Comment by liuzhenghua** [comment]
![image](https://github.com/gitbito/CLI/assets/11787325/938851dc-e85e-4a21-b476-8d88f4ef4c19)

**Comment by liuzhenghua** [comment]
When using Chinese, the probability of this problem occurring is particularly high.

**Comment by liuzhenghua** [comment]
![image](https://github.com/gitbito/CLI/assets/11787325/c32e4a5c-273f-423b-bd2e-251a779c6d28)

**Comment by macky3099** [comment]
@liuzhenghua let us check it on our end and get back to you with updates.

Thanks!

**Comment by macky3099** [comment]
Hello @liuzhenghua, 

We have fixed this issue in the new version of Bito CLI 3.6, can you please update and see if you are still facing the issue?

Thanks!

**Comment by macky3099** [comment]
Hello @liuzhenghua, we are closing this issue for now, please feel free to open it again if you face similar issues.
