### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cafe-old-babe** [gitbito/CLI#36]
<img width="1049" alt="image" src="https://github.com/gitbito/CLI/assets/38928746/dfa0d41a-ebcf-42dc-91af-b07c5e3129e7">

**Comment by macky3099** [comment]
Hi @cafe-old-babe, we are sorry for the issue you faced. Can you please share your log files with us to help us better understand what might have caused the issue.

Log files for Bito CLI can be found at:

1. For Mac/Linux: "/var/log/bito/bitocli.log"
2. For Windows: "C:\Users\your-user-name\AppData\Roaming\Bito\bitocli.log"

Thanks!

**Comment by macky3099** [comment]
Hello @cafe-old-babe, with the latest update of Bito CLI Version 3.7, we have fixed this issue. Can you please check and let us know if you still face any issues. Thanks!

**Comment by macky3099** [comment]
Hello @cafe-old-babe, I am closing this issue for now. Please feel free to reopen it if you face any issues further. Thanks!
