### ISSUE TITLE
bito.exe -p .\prompt.txt -f mycode.py command not working on windows

### ISSUE THREAD

**Issue by kaleyroy** [gitbito/CLI#4]
hello,  download  [BitoCLI.msi](https://github.com/gitbito/CLI/raw/main/version-1.0/BitoCLI.msi)
and install the binary, using the below command 

`.\bito.exe -p .\prompt.txt -f mycode.py `

**Got the Error: unknown shorthand flag: 'p' in -p**

![image](https://user-images.githubusercontent.com/1535437/233592562-23d29fb0-9ec6-43b5-b1df-4a57793c27e4.png)

**Comment by nisha-bito** [comment]
hi @kaleyroy ,

Can you please update Bito CLI to the latest version 3.0 in order to use -p and f options. 
Please ref to page - https://github.com/gitbito/CLI/tree/main/version-3.0 to download the latest version. 

Let us know if you face any further issue.

Thanks,
Nisha

**Comment by kaleyroy** [comment]
Thanks ：）
So please help to update the windows installer link on READEME page which may confusing other people.

![image](https://user-images.githubusercontent.com/1535437/233814356-4b7c6fc9-3a76-4044-9e86-f8f0b82d98ec.png)


> hi @kaleyroy ,
> 
> Can you please update Bito CLI to the latest version 3.0 in order to use -p and f options. Please ref to page - https://github.com/gitbito/CLI/tree/main/version-3.0 to download the latest version.
> 
> Let us know if you face any further issue.
> 
> Thanks, Nisha

**Comment by macky3099** [comment]
Done, thanks. This will be taken care of going ahead.

**Comment by macky3099** [comment]
Closing this issue as README updated as per required.
