### ISSUE TITLE
How to "Continue"?

### ISSUE THREAD

**Issue by billcxx** [gitbito/CLI#43]
Instead of writing to a markdown file, I tried Bito to add doxygen documentations directly to my hpp files.
The problem is the generated file is not complete. I know this is not Bito's problem, because using the same prompt and source code file in the Chatgpt will give me similar incomplete results. But in chatgpt, I can say continue and AI will continue from where it stopped. How can I achieve similar things in Bito cli?

**Comment by macky3099** [comment]
Hi @billcxx, to achieve what you are looking for in Bito CLI you can make use of context.

By default Bito CLI keeps context of up to 20 requests in interactive mode (interactive mode means the one when you simply run "bito").

In non-interactive mode (which means when you run "bito -p -f" commands) you can make use of "-c" flag which will keep writing your context in a file and use it for your next request that you make. 

Example: "bito -p prompt.txt -c context.txt" 

(You can always edit the context size by editing the "max_context_entries" field set in your config file of Bito CLI. To access the config simply run "bito config -e").

Below are screenshots of few examples of how it can be done:

1. 
![Screenshot 2023-12-04 at 9 59 57 PM](https://github.com/gitbito/CLI/assets/61789690/23bccf03-4116-4818-b28b-cdd2f6007a15)

2. 
![Screenshot 2023-12-05 171646](https://github.com/gitbito/CLI/assets/61789690/a6200c16-269b-43fd-b5f2-c2a075191e7e)

Please let us know if you still face any issues. Thanks!

**Comment by macky3099** [comment]
Hi @billcxx, I am closing this issue for now. If you face any issues then please feel free to reopen it again. Thanks!
