### ISSUE TITLE
How to keep bito cli up-to-date if I installed from curl on macOS?

### ISSUE THREAD

**Issue by AllenDang** [gitbito/CLI#5]
as title state

**Comment by macky3099** [comment]
Hi @AllenDang 

Curl will always download the latest version of Bito CLI. But we are also working on auto-update feature within the CLI itself.

**Comment by amargoel98** [comment]
@AllenDang , hope this helps!

**Comment by macky3099** [comment]
@AllenDang let us know if this resolves the issue that you were looking for and if we can close this issue.
