### ISSUE TITLE
Error: Slash commands are not available for this session due to an configuration issue.

### ISSUE THREAD

**Issue by xuwei152** [gitbito/CLI#51]
I am using latest version 4.0, but I get error message shown below. I have tried to reinstall but the error still occurs.
![Clip_2024-03-20_19-03-18](https://github.com/gitbito/CLI/assets/51861161/6ba2e069-dccd-4bb1-8918-b0053d42ee35)

**Comment by macky3099** [comment]
Hello @xuwei152 

Sorry for the issue you are facing. 
Can you please share more details about the OS that you are using?

**Comment by xuwei152** [comment]
I am using centos 7 with z shell.
![Clip_2024-03-21_10-50-29](https://github.com/gitbito/CLI/assets/51861161/d9350765-fd46-42c3-9a4c-45023fa46599)

Because I don't have root permission, I just downloaded the executable and put it in the "bin" to install the bito CLI.

**Comment by macky3099** [comment]
@xuwei152 okay got it. Thank you for helping us with this details.

As of Bito CLI 4.0 version we have started giving slash commands support for which there is a change in how we setup the configuration of Bito CLI to run as expected. Generally this configuration is handled via the curl, homebrew and Windows installer. 

But for you, as you have manually downloaded the binary, this config got missed. Let us help you with this. 
All you need to do is download the files attached in below and copy them to the same folder where you put the Bito binary file (which is "bin" in your case as you mentioned). Once this is done, you can run Bito CLI once again and check if you are facing similar issues. Also please make sure that "bito-lca" and "bito-slashCommands.json" files have executable permission for your user. 

Let us know if you still face this issue. Meanwhile we will update our documentation with this information for the manual approach to install Bito CLI.

Thanks!

Please unzip this file and then copy paste its contents to the file path where "bito" binary is placed.
[Bito CLI 4.0 Dependencies.zip](https://github.com/gitbito/CLI/files/14681472/Bito.CLI.4.0.Dependencies.zip)

**Comment by xuwei152** [comment]
Thanks for your quickly replies. It works.
