### ISSUE TITLE
Request to make an AUR package

### ISSUE THREAD

**Issue by charlie39** [gitbito/CLI#6]
I am thinking of making an AUR package  for easier tracking and installation on arch and derivative systems.
I am thinking of naming it bito-ai-cli. Do let me know what you think.

**Comment by charlie39** [comment]
I have made an AUR package for this: https://aur.archlinux.org/packages/bito-cli .
Please add this in the Readme file as well

**Comment by macky3099** [comment]
Hi @charlie39, 

 Thank you for this, we can add this to our README file.

**Comment by charlie39** [comment]
@macky3099 thank you, i have already open a PR as regarding this. 
Also , few questions about the versioning of this product. As i can see the product uses only major versions or only major versions are availed here, so i wanted to know whether minor upgrades would be availed here as well in future ? like 3.1 , 3.2.2 and so on? or the it would stick to availing major versions like 3.0, 4.0 , 5.0 and so on?

**Comment by bitoandy** [comment]
Hi @charlie39 ,

We are planning to have minor upgrades and bug fixes which will have minor versions numbers like 3.X like 3.1, 3.2, ... we are planning to avoid version numbers like 3.1.1. So it will have version number like 3.0, 4.0 for major and 3.1 till 3.9 for minor versions in case there are any before any major release.

Appreciate your help on maintaining the AUR package.

Also will be great if you name the package as bito-cli.
