### ISSUE TITLE
How to completely uninstall Bito-cli on macOS?

### ISSUE THREAD

**Issue by xulcdev** [gitbito/CLI#8]
As the title suggests

**Comment by bitoandy** [comment]
Hi @xulcdev,

We are working on a quick uninstall script, so that you do not have to manually remove files for uninstall. Will update once the script is available.

**Comment by bitoandy** [comment]
Hi @xulcdev ,

Please refer to: https://github.com/gitbito/CLI#uninstalling-bito-cli for instructions to uninstall Bito CLI.

**Comment by macky3099** [comment]
Closing this issue as README file has now been updated with required details.
